name: Build
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0/5 * * * 1-5'

jobs:
  build:
    name: Check for release
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'legleux/rippled'
          path: rippled
          fetch-depth: 0

      - uses: actions/checkout@v2
        with:
          path: shr

      - name: Get last latest tag
        id: latest-tag
        run: |
          cd rippled && ls -l && echo $(git describe --abbrev=0 --tags)
          echo '::set-output name=TAG::$(git describe --abbrev=0 --tags)'
          echo '::set-output name=OTHER::someoutput'

      - name: ls -l
        run: ls -l

      - name: Show last tag
        run: |
          echo "The last tag is ${{ steps.latest-tag.outputs.TAG }}"
          echo "The other output is ${{ steps.latest-tag.outputs.OTHER }}"

      - name: touch README.md
        run: cd shr && echo "$(date)-${{ steps.latest-tag.outputs.TAG }}" > README.md

      - name: Commit README.md
        run: |
          cd shr
          git config --global user.name 'Autobot'
          git config --global user.email 'autobot@example.com'
          git add README.md
          git commit -m"Automatic commit"
          git push